### PR TITLE
[IMP] Run black

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Review by simahawk — CHANGES_REQUESTED** [review]
IMO we should have pre-commit to make sure this is the same for every one and that it gets mandatory

**Review by simahawk — COMMENTED** [review]
thanks Max! Just one thing: I fear it makes it useless if it doesn't run on CI. 
You can add it on another PR if you prefer to speed up your other PRs.

**Comment by max3903** [comment]
@simahawk I think Actions need to be activated on the repo...

**Comment by simahawk** [comment]
it seems there's nothing to enable. Let's see what happens when it lands on master.

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
it's running here https://github.com/camptocamp/anthem/runs/3168660254 :tada:

**Comment by simahawk** [comment]
it failed, can you check?

**Comment by max3903** [comment]
> it failed, can you check?

#62

**Pull request merged**
