### PR TITLE
[IMP] Support for Odoo 15

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Comment by max3903** [comment]
@florentx Not sure why there is no pull request for this so creating it.

Anthem is working for Odoo 15 with those changes.

CC: @osimallen

**Review by florentx — APPROVED** [review]
LGTM (as I'm the author)

Bec I still work with v14, I've forgotten to create the PR. Good you've found it.

**Comment by florentx** [comment]
Well, actually it was already merged #63 in October last year

**Comment by max3903** [comment]
@yvaucher Any chance version 0.8.0 (or 1.0.0) can be released? Thanks!

**Pull request closed without merging**
