### PR TITLE
[WIP] Add odoov11 

### PR DESCRIPTION
**Pull request by leemannd**
Changes made to test locally anthem against python3 and odoo 11

### CODE REVIEW

**Comment by guewen** [comment]
If you find why the tests are failing it would be so nice :D

**Comment by leemannd** [comment]
@guewen I putted the begin of the explanation into the JIRA ticket. You are calling an invoke command that doesn't exist at all. Travis says `No idea what 'tests.prepare_config' is!`

**Comment by guewen** [comment]
Hmmm, it's there https://github.com/camptocamp/anthem/blob/master/tasks.py#L99

In master, the tests were failing with an odoo error

**Comment by guewen** [comment]
@leemannd okay this is a recent thing, probably due to a change in the invoke api then. I didn't check because previously tests were already sometimes failing with: https://travis-ci.org/camptocamp/anthem/builds/256899274#L379

**Comment by TDu** [comment]
Regarding the Travis error about tests.prepare_config.
It is due to this : http://docs.pyinvoke.org/en/latest/concepts/namespaces.html#dashes-vs-underscores
And a fix is added here #29 
Now to the next Travis error...

**Comment by guewen** [comment]
Superseeded by #29

**Comment by guewen** [comment]
Sorry, not superseeded by #29  :)

**Comment by leemannd** [comment]
@guewen Things are a bit mixup also in marabunta PR's. We should keep only one

**Comment by guewen** [comment]
Replaced by #29

**Pull request closed without merging**
