### PR TITLE
[WIP] log songs

### PR DESCRIPTION
**Pull request by guewen**
Example:

```python

    from anthem import log

    @log
    def setup_company(ctx):
        """ Setup company """
        # do stuff
        with ctx.log('other stuff'):
            # do other stuff

    @log
    def load_data(ctx):
        """ Load data """
        # load

    @log
    def main(ctx):
        setup_company(ctx)
        load_data(ctx)
```
 If we run anthem on ``main``, we will get:

    running... main
       running... Setup company
          running... other stuff
          other stuff: 0.850s
       Setup company: 1.100s
       running... Load data
       Load data: 2.900s
    main: 4.000s

### CODE REVIEW

**Comment by guewen** [comment]
@mdietrichc2c @yvaucher 

Wanted!

* reviews
* opinions on the output
* opinions on the API for using it
* a name related to songs / music to use instead of the bleak `log`

**Comment by yvaucher** [comment]
a name related to songs / music to use instead of the bleak log

* record
* album
* (audio)tape
* cassette

Pour les logs je sais pas si de faire ainsi serait pas plus lisible au premier coup d'oeil en retirant le décalage:

```
main running... 
   Setup company running... 
      other stuff running...
      other stuff: 0.850s
   Setup company: 1.100s
   Load data running... 
   Load data: 2.900s
main: 4.000s
```

En tout cas mon cerveau fait matcher beaucoup plus vide ou cela commence et ou cela termine.

Sinon :+1:

**Comment by guewen** [comment]
Changed to

```
main... 
   Setup company... 
      other stuff...
      other stuff: 0.850s
   Setup company: 1.100s
   Load data... 
   Load data: 2.900s
main: 4.000s
```

Without the `running` which might sound weird at the end of some description.

Thanks for the naming proposals, but they're rather technical / physical, we are in a more abstract registry with anthem, songs, lyrics. As it is a matter of producing output with words, as was more thinking of something in the like of vocals, choral, voice (or growl :). But, after more thinking, I fear that it would obfuscate the code too much, would make the API too unexpected. What do you think?

**Comment by yvaucher** [comment]
It could be `LP` but you would have to limit the size of recording to 45 minutes.

For me the songs could be written down or recorded. What we want with logs is to know what was precisely sung. The issue is that writting down a song is more the procedure/recipe/code instead of a log. A choral or vocals would more be an execution of the song. Thus at least you need a gramophone record. Maybe `vinyl` would be abstract enough but not too obfuscated ?

**Comment by guewen** [comment]
I'd agree with you if we were recording something, but we aren't. We are just outputting text to stdout (which is a bit analogue to producing words in the air :).

**Comment by mdietrichc2c** [comment]
Since it's all about measuring the performance of a song, I'd say `concert` or `live show`.

Re: output and all, that's much needed, so :+1:

**Comment by yvaucher** [comment]
```
recital

1. a musical entertainment given usually by a single performer or by a performer and one or more accompanists. 
[...]
6. a detailed statement. 
```

Source: http://www.dictionary.com/browse/recital

**Pull request merged**
